// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhR_iVfW7l09DkLP5_uif_Dz9-miVlYLs',
    appId: '1:863495640912:web:5a4dfd190dfbfe81523e55',
    messagingSenderId: '863495640912',
    projectId: 'vuanhduc-chinese-vocab',
    authDomain: 'vuanhduc-chinese-vocab.firebaseapp.com',
    storageBucket: 'vuanhduc-chinese-vocab.firebasestorage.app',
    measurementId: 'G-NLJT808MHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6LRgO-XFwMYcYETGZ52VIDvS-iD6tXy4',
    appId: '1:863495640912:android:ef621d2005189526523e55',
    messagingSenderId: '863495640912',
    projectId: 'vuanhduc-chinese-vocab',
    storageBucket: 'vuanhduc-chinese-vocab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhR_iVfW7l09DkLP5_uif_Dz9-miVlYLs',
    appId: '1:863495640912:web:8e94157e92bcfeda523e55',
    messagingSenderId: '863495640912',
    projectId: 'vuanhduc-chinese-vocab',
    authDomain: 'vuanhduc-chinese-vocab.firebaseapp.com',
    storageBucket: 'vuanhduc-chinese-vocab.firebasestorage.app',
    measurementId: 'G-BXQP9MMY6B',
  );
}
